In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr1.shape

(5,)

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2.shape

(2, 3)

In [9]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
arr3.shape

(2, 2, 2)

In [11]:
arr3.ndim

3

In [12]:
arr2.ndim

2

In [13]:
arr1.ndim

1

In [14]:
arr3.size

8

In [15]:
arr2.size

6

In [16]:
arr1.size

5

In [17]:
#byte
arr3.itemsize

4

In [19]:
arr3.dtype

dtype('int32')

In [20]:
arr4=np.linspace(10,20,10)
arr4

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [21]:
arr4.dtype

dtype('float64')

In [23]:
#changes datatype
arr3.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])