In [15]:
import numpy as np

In [5]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
b=np.array([[1,2,3],[5,6,7]])
b

array([[1, 2, 3],
       [5, 6, 7]])

In [11]:
type(b)

numpy.ndarray

In [4]:
c=np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
d=np.ones((2,3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
e=np.identity(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
f=np.arange(10)
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
f=np.arange(5,16)
f

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
f=np.arange(5,16,2)
f

array([ 5,  7,  9, 11, 13, 15])

In [10]:
g=np.linspace(10,20,10)
g

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [11]:
h=g.copy()
h

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])